### ISSUE TITLE
app crashes when orientation changes

### ISSUE THREAD

**Issue by ShihaoXu** [ShihaoXu/Go-Prototype#2]
1. Enter app -> change to landscape -> set an event as main -> crash
2. `08-03 18:47:10.060 9750-9750/edu.kit.sose2017go4.goprototype E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: edu.kit.sose2017go4.goprototype, PID: 9750
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.FragmentTransaction android.app.FragmentManager.beginTransaction()' on a null object reference
                                                                                   at edu.kit.sose2017go4.goprototype.viewcontroller_observer.NextEventFragment.update(NextEventFragment.java:150)
                                                                                   at edu.kit.sose2017go4.goprototype.viewcontroller_subject.NextEventSubject.notifyObserver(NextEventSubject.java:90)
                                                                                   at edu.kit.sose2017go4.goprototype.viewcontroller_observer.EventListAdapter$EventVH$1.onMenuItemClick(EventListAdapter.java:109)
                                                                                   at android.support.v7.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:250)
                                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
                                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
                                                                                   at android.support.v7.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
                                                                                   at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                                   at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
                                                                                   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3132)
                                                                                   at android.widget.AbsListView$3.run(AbsListView.java:4047)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`

**Comment by ShihaoXu** [comment]
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);


        eventListAdapter = new EventListAdapter(getActivity(), EventListSubject.getInstance(getContext()), NextEventSubject.getInstance());
        eventRV.setAdapter(eventListAdapter);
        eventRV.setLayoutManager(new LinearLayoutManager(getActivity()));

        EventListSubject.getInstance(getContext()).registerObserver(this);
        EventListSubject.getInstance(getContext()).notifyObserver();
    }

**Comment by ShihaoXu** [comment]
@Override
public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        eventListAdapter = new EventListAdapter(getActivity(), EventListSubject.getInstance(getContext()), NextEventSubject.getInstance());
        eventRV.setAdapter(eventListAdapter);
        eventRV.setLayoutManager(new LinearLayoutManager(getActivity()));
        EventListSubject.getInstance(getContext()).registerObserver(this);
        EventListSubject.getInstance(getContext()).notifyObserver();
    }

**Comment by ShihaoXu** [comment]
EventOverviewFragment.java:

    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        eventListAdapter = new EventListAdapter(getActivity(), EventListSubject.getInstance(getContext()), NextEventSubject.getInstance());
        eventRV.setAdapter(eventListAdapter);
        eventRV.setLayoutManager(new LinearLayoutManager(getActivity()));
        EventListSubject.getInstance(getContext()).registerObserver(this);
        EventListSubject.getInstance(getContext()).notifyObserver();
    }
